### ISSUE TITLE
There is a problem with the engine playing white or black moves

### ISSUE THREAD

**Issue by MianmianYingxiang** [rooklift/ogatak#120] opened 2024-03-01 09:40 UTC
If the engine is selected in the settings to execute white chess, then black chess will also be calculated by the engine. On the contrary, if the engine executes black chess, white chess will also be calculated. This exists in versions after 1.9.3.

**Comment by rooklift** [comment] 2024-03-01 14:05
I can't reproduce this. Can you give exact reproduction steps?

**Comment by MianmianYingxiang** [comment] 2024-03-02 01:17
> However, I wonder if there's some confusion about what those options do. Those are designed to let you play against KataGo, i.e. you play a move and the computer plays a move for the other side, repeatedly. They don't do anything else...

Sorry, I am Chinese, and my English expression may not be accurate. This should be a small BUG. For example, if I play black, I select the engine to play white in the settings, but when the game starts, the engine will also calculate black on the interface. I can see the selection point of the black chess piece. I think the calculation should be stopped when the chess piece is black, because the engine is playing the white chess piece.

**Comment by rooklift** [comment] 2024-03-02 12:12
This doesn't happen for me.


https://github.com/rooklift/ogatak/assets/16438795/99d34bd8-948c-42fc-8e10-a87b6021bcd8

**Comment by MianmianYingxiang** [comment] 2024-03-03 02:05
> 这不会发生在我身上。
> 
>  2024-03-02.12-11-08.mov

It may be a problem with my computer configuration. My operating system is Windows 7, or it may be other problems.

**Comment by MianmianYingxiang** [comment] 2024-03-03 02:20
> 这不会发生在我身上。
> 
>  2024-03-02.12-11-08.mov


Uploading QQ录屏20240303101604-cut-merged-1709432267145.mp4…

It may be a problem with my computer configuration. My operating system is Windows 7, or it may be other problems.This will not happen in versions prior to 1.9.3

**Comment by MianmianYingxiang** [comment] 2024-03-03 02:24
> 2024-03-02.12-11-08.mov

https://github.com/rooklift/ogatak/assets/161823921/6815a2cf-0767-4971-9dd5-d521c253d714

It may be a problem with my computer configuration. My operating system is Windows 7, or it may be other problems.This will not happen in versions prior to 1.9.3

**Comment by MianmianYingxiang** [comment] 2024-03-03 02:31
> This doesn't happen for me.
> 
>  2024-03-02.12-11-08.mov


https://github.com/rooklift/ogatak/assets/161823921/11242ea5-5fcf-4860-852d-c59c1e78653a

It may be a problem with my computer configuration. My operating system is Windows 7, or it may be other problems.This will not happen in versions prior to 1.9.3

**Comment by rooklift** [comment] 2024-03-03 11:24
Thanks, I understand now. I'll look into it.

**Comment by MianmianYingxiang** [comment] 2024-03-03 11:37
> Thanks, I understand now. I'll look into it.

感谢

**Comment by rooklift** [comment] 2024-03-03 11:52
This should be fixed in 2.0.6, which I am uploading now. Please let me know.

**Comment by MianmianYingxiang** [comment] 2024-03-03 12:28
> This should be fixed in 2.0.6, which I am uploading now. Please let me know.

I just tried it and the problem was fixed, thank you

**Closed** 2024-03-03 13:37 UTC
Labels: bug
